/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdc_yzu_myndk_MainActivity */

#ifndef _Included_com_asdc_yzu_myndk_MainActivity
#define _Included_com_asdc_yzu_myndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asdc_yzu_myndk_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_asdc_yzu_myndk_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_asdc_yzu_myndk_MainActivity
 * Method:    FindFeatures
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_asdc_yzu_myndk_MainActivity_FindFeatures
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
